### PR TITLE
Reduce memory consumption

### LINKED ISSUE #1712: Memory consumption by trimming the rows and cells
**Description**

By having a lot of rows and columns, memory consumption increases a lot. The reason is that we always allocate a new underlying array instead of re-using the existing one.

**Steps to reproduce the issue:**
1. By trying to convert a huge amount of rows (30000+) into the xlsx

**Describe the results you received:**

trimCell issue:
heap1

trimRow issue: (append)
heap-append

**Describe the results you expected:**

We can reusing the existing underlying array instead of always allocating a new one.

**Output of `go version`:**

```text
1.21
```

**Excelize version or commit ID:**

```text
v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

### PR DESCRIPTION
**Pull request by krstak**
# PR Details

Reduce memory consumption

## Description
By having a lot of rows and columns, memory consumption increases a lot. The reason is that we always allocate a new underlying array instead of re-using the existing one.

## Related Issue

https://github.com/qax-os/excelize/issues/1712

## Motivation and Context

By having a huge amount of rows, the library consumes a lot of memory for converting it to the xlsx file. After this change, a lot of memory would be saved.

## How Has This Been Tested

I tried to convert a huge amount of data (60000 rows) to the xlsx 

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: sheet.go [hunk 1]
```diff
@@ -178,36 +178,38 @@ func (f *File) workSheetWriter() {
 // trimRow provides a function to trim empty rows.
 func trimRow(sheetData *xlsxSheetData) []xlsxRow {
 	var (
-		row  xlsxRow
-		rows []xlsxRow
+		row xlsxRow
```
Comment (xuri) [inline sheet.go:181]: This can be simplify to `var row xlsxRow`.

**Review by xuri — CHANGES_REQUESTED** [review]

File: sheet.go (hunk 1 above)
Comment (krstak) [reply sheet.go]: Correct. Done.

File: sheet.go [hunk 2]
```diff
@@ -177,37 +177,38 @@ func (f *File) workSheetWriter() {
 
 // trimRow provides a function to trim empty rows.
 func trimRow(sheetData *xlsxSheetData) []xlsxRow {
-	var (
-		row  xlsxRow
-		rows []xlsxRow
-	)
-	for k, v := range sheetData.Row {
+	var row xlsxRow
```
Comment (xuri) [inline sheet.go:180]: Declare variable in the same way we be better (rename nextIndex to i):

```go
var (
    row xlsxRow
    i   int
)
```

**Review by xuri — CHANGES_REQUESTED** [review]

File: sheet.go (hunk 2 above)
Comment (krstak) [reply sheet.go]: Done.

Comment (xuri) [reply sheet.go]: Thanks for your great work. Could you run a new pprof figure to show how much memory was reduced in the optimization?

**Review by xuri — COMMENTED** [review]
Thanks for your great work. Could you run a new pprof figure to show how much memory was reduced in the optimization?

**Comment by krstak** [comment]
> Thanks for your great work. Could you run a new pprof figure to show how much memory was reduced in the optimization?

You are welcome.

I've already done it and pprof didn't show the problem anymore. It didn't show anything related to that problem. Since there are other potential memory consumption data issues, pprof pointed me to the new place that uses ~192MB. That place is in the function prepareSheetXML where we use append `ws.SheetData.Row = append(ws.SheetData.Row, ...)`

Since I am not 100% familiar with the code and it seems I would need to re-read a whole codebase to safely change that part, I didn't want to touch it. 

mem_problem

**Review by xuri — APPROVED** [review]
LGTM, thanks for your contribution.

**Comment by xuri** [comment]
Note that this PR introduce regression for issue #1383, fixed by issue #2335.
