### PR TITLE
1820 Bug - Convert styleFillVariants from slice to func

### LINKED ISSUE #1820: Different gradient fill colors return the same style index
Different gradient fills produce the same style index making it impossible to use more than one gradient fill in a workbook.

```go
package main

import (
	"fmt"
	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()

	s1 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 1,
			Shading: 1,
			Color:   []string{"#000000", "#FFFFFF"},
		},
	}

	s2 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 1,
			Shading: 1,
			Color:   []string{"#FFFF00", "#000000"},
		},
	}

	s1Index, _ := f.NewStyle(&s1)
	s2Index, _ := f.NewStyle(&s2)

	fmt.Println("s1Index:", s1Index)
	fmt.Println("s2Index:", s2Index)
}

```

**Describe the results you received:**

```bash
s1Index: 1
s2Index: 1
```

**Describe the results you expected:**
```bash
s1Index: 1
s2Index: (Something other than 1)
```

**Output of `go version`:**

```text
go version go1.22.0 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

```text
Apple M2 Max (Mac OS 14.2.1)
```

### PR DESCRIPTION
**Pull request by edwardfward**
# PR Details

Fixes a bug with gradient fill styles that was causing different colored fills to return the same `styleID` making it impossible to use more than one gradient fill per workbook.

## Description

Changed the `styleFillVariants` variable from `[]xlsxGradientFill` to `func() []xlsxGradientFill` per @xuri's recommendation.

## Related Issue

* Closes #1820 

## Motivation and Context

Customer required several gradient fills in the workbook we were generating for them. This PR allows use to generate those gradient fills.

## How Has This Been Tested

* Added unit test to verify gradients did not produce the same `styleID`
* Executed `go test ./...`
```text
ok      github.com/xuri/excelize/v2     23.656s
```

* Executed the following test program to verify the fills we required returned unique `styleID`
```go
package main

import (
	"fmt"
	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()

	s1 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 4,
			Shading: 1,
			Color:   []string{"#000000", "#FFFFFF"},
		},
	}

	s2 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 2,
			Shading: 1,
			Color:   []string{"#FFFF00", "#000000"},
		},
	}

	s1Index, err := f.NewStyle(&s1)
	if err != nil {
		fmt.Println(err)
		return

	}
	s2Index, _ := f.NewStyle(&s2)

	fmt.Println("s1Index:", s1Index)
	fmt.Println("s2Index:", s2Index)
}
```
Result:
```text
s1Index: 1
s2Index: 2
```

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: styles_test.go [hunk 1]
```diff
@@ -356,7 +365,7 @@ func TestNewStyle(t *testing.T) {
 		CustomNumFmt: &numFmt,
 	})
 	assert.NoError(t, err)
-	assert.Equal(t, 2, styleID)
+	assert.Equal(t, 1, styleID)
```
Comment (edwardfward) [inline styles_test.go:368]: Adjusted index due to `NewFile()`

**Review by xuri — APPROVED** [review]
LGTM, thanks for your contribution.
